/*~ Welcome to the hsm PROXY daemon (SeqLN Tier-2, milestone M1)!
 *
 * This is a MODIFIED COPY of hsmd/hsmd.c.  It keeps ALL of the ccan/io + fd
 * machinery, the per-subdaemon fd multiplexing (WIRE_HSMD_CLIENT_HSMFD via
 * socketpair + SCM_RIGHTS), the client bookkeeping and the capability checks,
 * so from lightningd's point of view it IS the hsmd (fd 3 speaks the hsmd wire).
 *
 * The one thing it does NOT do is keep the root secret or run libhsmd's crypto:
 * it holds no hsm_secret and never calls hsmd_init / hsmd_handle_client_message.
 * Instead it fork/exec's a separate `signerd` process (hsmd/signerd.c) sharing
 * our working directory, and for every request that needs the secret it forwards
 * a framed {client_ctx, hsmd_msg} to signerd (see hsmd/signer_frame.h) and
 * relays signerd's reply back to the client.  fd multiplexing stays 100% local
 * here, exactly as the Tier-2 design requires.
 *
 * We still link libhsmd, but only for the pure `hsmd_check_client_capabilities`
 * helper (and the dev flag globals); no secret is ever loaded in this process.
 */
#include "config.h"
#include <bitcoin/privkey.h>
#include <bitcoin/pubkey.h>
#include <ccan/array_size/array_size.h>
#include <ccan/intmap/intmap.h>
#include <ccan/io/fdpass/fdpass.h>
#include <ccan/noerr/noerr.h>
#include <ccan/read_write_all/read_write_all.h>
#include <ccan/str/hex/hex.h>
#include <ccan/tal/grab_file/grab_file.h>
#include <ccan/tal/path/path.h>
#include <ccan/tal/str/str.h>
#include <ccan/time/time.h>
#include <common/daemon_conn.h>
#include <common/memleak.h>
#include <common/status.h>
#include <common/status_wiregen.h>
#include <common/subdaemon.h>
#include <common/timeout.h>
#include <common/utils.h>
#include <errno.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <poll.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
/*~ _wiregen files are autogenerated by tools/generate-wire.py */
#include <hsmd/libhsmd.h>
#include <hsmd/permissions.h>
#include <hsmd/signer_frame.h>
#include <hsmd/signer_noise.h>
#include <wire/wire_io.h>
#include <wire/wire_sync.h>

/*~ Each subdaemon is started with stdin connected to lightningd (for status
 * messages), and stderr untouched (for emergency printing).  File descriptors
 * 3 and beyond are set up on other sockets: for hsmd, fd 3 is the request
 * stream from lightningd. */
#define REQ_FD 3

/*~ The single transport to our out-of-process signerd (set up in main before
 * the io_loop).  All secret-bearing requests are forwarded over this fd. */
static int signer_fd = -1;

/*~ Set (non-NULL) ONLY in the remote/network mode: the BOLT-8 Noise_XK secured
 * channel to the device signer.  When set, requests are tunneled through it
 * (encrypted + mutually authenticated) instead of over the raw `signer_fd`.
 * NULL in the default local fork+socketpair mode (trusted local UNIX socket).
 * In LISTEN mode it may transiently be NULL while a dropped device reconnects. */
static struct signer_noise *signer_noise;

/*~ LISTEN mode (BROWSER topology) is RECONNECTABLE: a browser device can close
 * (tab close/reopen, network blip) and come back, so we keep the listen socket
 * open for the proxy's lifetime and re-accept + re-authenticate a fresh device
 * whenever the current one drops.  These hold what we need to do that without
 * re-reading the environment.  `signer_listen_mode` is false in ADDR/connect
 * mode and local-fork mode, whose behaviour is unchanged. */
static bool signer_listen_mode;
static int signer_listen_fd = -1;
static struct secret signer_listen_priv;   /* our transport static privkey */
static struct pubkey signer_listen_pinned; /* the pinned device static pubkey */

/*~ Session priming (LISTEN mode).  The device derives every key from its
 * hsm_secret per-request, BUT two pieces of in-memory state are set up by
 * earlier requests that lightningd sends only ONCE (at boot), never again:
 *
 *   - WIRE_HSMD_INIT builds the device's signing kernel (node key + the
 *     network-specific BIP32 versions).  Without it EVERY later request is
 *     refused by the device ("not initialized").
 *   - WIRE_HSMD_SETUP_CHANNEL records a channel's parameters; without it an
 *     enforce-policy device refuses that channel's commitment signatures.
 *
 * So a freshly-reconnected device is NOT ready to serve until we replay these.
 * We cache the INIT (with its reply, for an identity guard) plus the latest
 * SETUP_CHANNEL per channel dbid, and replay them right after every fresh
 * device handshake, discarding the (deterministic) replies.  This is why the
 * reconnect resumes serving ALL of lightningd's multiplexed clients, not just
 * the one whose request was in flight. */
struct primed_req {
	bool is_main;
	struct node_id id;
	u64 dbid;
	u64 capabilities;
	const u8 *msg; /* raw hsmd wire message, tal child of this struct */
};
static const tal_t *prime_ctx;
static struct primed_req *primed_init;
static u8 *primed_init_reply;
static UINTMAP(struct primed_req *) primed_setup; /* dbid -> setup_channel */

/*~ We keep track of clients, but there's not much to keep. */
struct client {
	/* The ccan/io async io connection for this client: it closes, we die. */
	struct io_conn *conn;

	/*~ io_read_wire needs a pointer to store incoming messages until
	 * it has the complete thing; this is it. */
	u8 *msg_in;

	/*~ Useful for logging, but also used to derive the per-channel seed. */
	struct node_id id;

	/*~ This is a unique value handed to us from lightningd, used for
	 * per-channel seed generation (a single id may have multiple channels
	 * over time).
	 *
	 * It's actually zero for the initial lightningd client connection and
	 * the ones for gossipd and connectd, which don't have channels
	 * associated. */
	u64 dbid;

	/* What is this client allowed to ask for? */
	u64 capabilities;

	/* Params to apply to all transactions for this client */
	const struct chainparams *chainparams;

	/* Client context to pass over to libhsmd for its calls. */
	struct hsmd_client *hsmd_client;
};

/*~ We keep a map of nonzero dbid -> clients, mainly for leak detection.
 * This is ccan/uintmap, which maps u64 to some (non-NULL) pointer.
 * I really dislike these kinds of declaration-via-magic macro things, as
 * tags can't find them without special hacks, but the payoff here is that
 * the map is typesafe: the compiler won't let you put anything in but a
 * struct client pointer. */
static UINTMAP(struct client *) clients;
/*~ Plus the three zero-dbid clients: master, gossipd and connnectd. */
static struct client *dbid_zero_clients[3];
static size_t num_dbid_zero_clients;

/* Are we in developer mode */
static bool developer;

/*~ We need this deep inside bad_req_fmt, and for memleak, so we make it a
 * global. */
static struct daemon_conn *status_conn;

/* This is used for various assertions and error cases. */
static bool is_lightningd(const struct client *client)
{
	return client == dbid_zero_clients[0];
}

/* Pre-declare this, due to mutual recursion */
static struct io_plan *handle_client(struct io_conn *conn, struct client *c);

/*~ ccan/compiler.h defines PRINTF_FMT as the gcc compiler hint so it will
 * check that fmt and other trailing arguments really are the correct type.
 *
 * This is a convenient helper to tell lightningd we've received a bad request
 * and closes the client connection.  This should never happen, of course, but
 * we definitely want to log if it does.
 */
static struct io_plan *bad_req_fmt(struct io_conn *conn,
				   struct client *c,
				   const u8 *msg_in,
				   const char *fmt, ...)
	PRINTF_FMT(4,5);

static struct io_plan *bad_req_fmt(struct io_conn *conn,
				   struct client *c,
				   const u8 *msg_in,
				   const char *fmt, ...)
{
	va_list ap;
	char *str;

	va_start(ap, fmt);
	str = tal_vfmt(tmpctx, fmt, ap);
	va_end(ap);

	/*~ If the client was actually lightningd, it's Game Over; we actually
	 * fail in this case, and it will too. */
	if (is_lightningd(c)) {
		status_broken("%s", str);
		master_badmsg(fromwire_peektype(msg_in), msg_in);
	}

	/*~ Nobody should give us bad requests; it's a sign something is broken */
	status_broken("%s: %s", fmt_node_id(tmpctx, &c->id), str);

	/*~ Note the use of NULL as the ctx arg to towire_hsmstatus_: only
	 * use NULL as the allocation when we're about to immediately free it
	 * or hand it off with take(), as here.  That makes it clear we don't
	 * expect it to linger, and in fact our memleak detection will
	 * complain if it does (unlike using the deliberately-transient
	 * tmpctx). */
	daemon_conn_send(status_conn,
			 take(towire_hsmstatus_client_bad_request(NULL,
								  &c->id,
								  str,
								  msg_in)));

	/*~ The way ccan/io works is that you return the "plan" for what to do
	 * next (eg. io_read).  io_close() is special: it means to close the
	 * connection. */
	return io_close(conn);
}

/* Convenience wrapper for when we simply can't parse. */
static struct io_plan *bad_req(struct io_conn *conn,
			       struct client *c,
			       const u8 *msg_in)
{
	return bad_req_fmt(conn, c, msg_in, "could not parse request");
}

/*~ This plan simply says: read the next packet into 'c->msg_in' (parent 'c'),
 * and then call handle_client with argument 'c' */
static struct io_plan *client_read_next(struct io_conn *conn, struct client *c)
{
	c->msg_in = tal_free(c->msg_in);
	return io_read_wire(conn, c, &c->msg_in, handle_client, c);
}

/*~ This is the destructor on our client: we may call it manually, but
 * generally it's called because the io_conn associated with the client is
 * closed by the other end. */
static void destroy_client(struct client *c)
{
	if (!uintmap_del(&clients, c->dbid))
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "Failed to remove client dbid %"PRIu64, c->dbid);
}

static struct client *new_client(const tal_t *ctx,
				 const struct chainparams *chainparams,
				 const struct node_id *id,
				 u64 dbid,
				 const u64 capabilities,
				 int fd)
{
	struct client *c = tal(ctx, struct client);

	c->msg_in = NULL;

	/*~ All-zero pubkey is used for the initial master connection */
	if (id) {
		c->id = *id;
		if (!node_id_valid(id))
			status_failed(STATUS_FAIL_INTERNAL_ERROR,
				      "Invalid node id %s",
				      fmt_node_id(tmpctx, id));
	} else {
		memset(&c->id, 0, sizeof(c->id));
	}
	c->dbid = dbid;

	c->capabilities = capabilities;
	c->chainparams = chainparams;

	/*~ This is the core of ccan/io: the connection creation calls a
	 * callback which returns the initial plan to execute: in our case,
	 * read a message.*/
	c->conn = io_new_conn(ctx, fd, client_read_next, c);

	/*~ tal_steal() moves a pointer to a new parent.  At this point, the
	 * hierarchy is:
	 *
	 *   ctx -> c
	 *   ctx -> c->conn
	 *
	 * We want to the c->conn to own 'c', so that if the io_conn closes,
	 * the client is freed:
	 *
	 *   ctx -> c->conn -> c.
	 */
	tal_steal(c->conn, c);

	/* We put the special zero-db HSM connections into an array, the rest
	 * go into the map. */
	if (dbid == 0) {
		assert(num_dbid_zero_clients < ARRAY_SIZE(dbid_zero_clients));
		dbid_zero_clients[num_dbid_zero_clients++] = c;
		c->hsmd_client = hsmd_client_new_main(c, c->capabilities, c);
	} else {
		struct client *old_client = uintmap_get(&clients, dbid);

		/* Close conn and free any old client of this dbid. */
		if (old_client)
			io_close(old_client->conn);

		if (!uintmap_add(&clients, dbid, c))
			status_failed(STATUS_FAIL_INTERNAL_ERROR,
				      "Failed inserting dbid %"PRIu64, dbid);
		tal_add_destructor(c, destroy_client);
		c->hsmd_client =
		    hsmd_client_new_peer(c, c->capabilities, dbid, id, c);
	}

	return c;
}

/* This is the common pattern for the tail of each handler in this file. */
static struct io_plan *req_reply(struct io_conn *conn,
				 struct client *c,
				 const u8 *msg_out TAKES)
{
	/*~ Write this out, then read the next one.  This works perfectly for
	 * a simple request/response system like this.
	 *
	 * Internally, the ccan/io subsystem gathers all the file descriptors,
	 * figures out which want to write and read, asks the OS which ones
	 * are available, and for those file descriptors, tries to do the
	 * reads/writes we've asked it.  It handles retry in the case where a
	 * read or write is done partially.
	 *
	 * Since the OS does buffering internally (on my system, over 100k
	 * worth) writes will normally succeed immediately.  However, if the
	 * client is slow or malicious, and doesn't read from the socket as
	 * fast as we're writing, eventually the socket buffer will fill up;
	 * we don't care, because ccan/io will wait until there's room to
	 * write this reply before it will read again.  The client just hurts
	 * themselves, and there's no Denial of Service on us.
	 *
	 * If we were to queue outgoing messages ourselves, we *would* have to
	 * consider such scenarios; this is why our daemons generally avoid
	 * buffering from untrusted parties. */
	return io_write_wire(conn, msg_out, client_read_next, c);
}

/*~ Fork+exec our signerd child, wiring one socket between us.  We are the
 * parent; the child inherits our working directory (the lightning network dir),
 * which is where it loads/creates hsm_secret at init time.  This runs before the
 * io_loop, so signerd is ready by the time lightningd sends WIRE_HSMD_INIT. */
static void start_signerd(const char *proxy_argv0)
{
	int fds[2];
	const char *signerd_path;
	pid_t pid;

	if (socketpair(AF_UNIX, SOCK_STREAM, 0, fds) != 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "signerd socketpair: %s", strerror(errno));

	/* Explicit override first, else next to our own binary. */
	signerd_path = getenv("SEQLN_SIGNERD");
	if (!signerd_path)
		signerd_path = path_join(tmpctx,
					 path_dirname(tmpctx, proxy_argv0),
					 "lightning_signerd");

	pid = fork();
	if (pid < 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR, "signerd fork: %s",
			      strerror(errno));

	if (pid == 0) {
		/* Child: become signerd, talking on fds[1]. */
		char fdstr[16];
		close(fds[0]);
		snprintf(fdstr, sizeof(fdstr), "%d", fds[1]);
		execl(signerd_path, "lightning_signerd", fdstr, (char *)NULL);
		/* Only reached on exec failure. */
		fprintf(stderr, "hsmd-proxy: exec signerd (%s) failed: %s\n",
			signerd_path, strerror(errno));
		_exit(127);
	}

	/* Parent: keep our end. */
	close(fds[1]);
	signer_fd = fds[0];
	status_unusual("hsmd-proxy: started signerd pid %d on fd %d (%s)",
		       (int)pid, signer_fd, signerd_path);
}

/*~ Load a hex value from an env var, or (failing that) from the file named by a
 * second env var.  Returns a NUL-terminated tal string off `ctx`, or NULL. */
static char *hex_from_env_or_file(const tal_t *ctx, const char *env_key,
				  const char *file_key)
{
	const char *v = getenv(env_key);
	const char *path;
	char *s;

	if (v && v[0] != '\0')
		return tal_strdup(ctx, v);

	path = getenv(file_key);
	if (!path || path[0] == '\0')
		return NULL;
	s = grab_file_str(ctx, path);
	if (!s)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "could not read %s (%s)", file_key, path);
	/* Trim trailing whitespace/newline. */
	for (size_t n = strlen(s); n > 0; n--) {
		if (s[n - 1] == '\n' || s[n - 1] == '\r'
		    || s[n - 1] == ' ' || s[n - 1] == '\t')
			s[n - 1] = '\0';
		else
			break;
	}
	return s;
}

/*~ Load the proxy's own transport static privkey (SEQLN_HOST_PRIVKEY[_FILE]). */
static void load_host_privkey(struct secret *priv)
{
	char *h = hex_from_env_or_file(tmpctx, "SEQLN_HOST_PRIVKEY",
				       "SEQLN_HOST_PRIVKEY_FILE");
	if (!h)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "remote signer mode requires SEQLN_HOST_PRIVKEY"
			      " (or SEQLN_HOST_PRIVKEY_FILE): the proxy's own"
			      " transport static privkey");
	if (!hex_decode(h, strlen(h), priv->data, sizeof(priv->data)))
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "SEQLN_HOST_PRIVKEY must be 32 bytes (64 hex chars)");
}

/*~ Load the pinned device-signer static pubkey (SEQLN_SIGNER_PEER_PUBKEY): the
 * ONLY signer identity this proxy will authenticate + talk to. */
static void load_pinned_signer_pubkey(struct pubkey *pub)
{
	const char *h = getenv("SEQLN_SIGNER_PEER_PUBKEY");
	u8 der[PUBKEY_CMPR_LEN];
	if (!h || h[0] == '\0')
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "remote signer mode requires SEQLN_SIGNER_PEER_PUBKEY"
			      " (the pinned device-signer static pubkey)");
	if (!hex_decode(h, strlen(h), der, sizeof(der))
	    || !pubkey_from_der(der, sizeof(der), pub))
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "SEQLN_SIGNER_PEER_PUBKEY must be a 33-byte"
			      " compressed pubkey (66 hex chars)");
}

/*~ SeqLN Tier-2 NETWORK transport.  Instead of fork/exec'ing a local signerd,
 * connect() over TCP to a REMOTE signer at `addr` ("host:port"), then run a
 * BOLT-8 Noise_XK handshake over it and tunnel every framed request through the
 * resulting SECURED channel (`signer_noise`).  This is what makes the "we host
 * the node, the device signs remotely" topology real AND safe: lightningd + this
 * proxy run on our box, the signer (and the hsm_secret) live on the user's
 * device, and the link between them is encrypted + mutually authenticated.
 *
 * Fail-closed: remote mode REQUIRES the pinned keys (SEQLN_HOST_PRIVKEY[_FILE] +
 * SEQLN_SIGNER_PEER_PUBKEY).  There is no unauthenticated remote fallback; the
 * only cleartext path is the local fork+socketpair (a trusted local UNIX
 * socket), which is unchanged.  Mirrored in
 * contrib/seqln-signer/src/bin/seqln-signer.rs (the responder).
 */
static void connect_remote_signer(const char *addr)
{
	char *host, *port, *colon;
	struct addrinfo hints, *res, *ai;
	struct privkey my_priv;
	struct pubkey pinned_signer, my_pub;
	int fd = -1, gai, one = 1;

	/* Load + validate the pinned keys BEFORE we touch the network, so a
	 * misprovisioned node fails loudly at boot rather than in the clear. */
	load_host_privkey(&my_priv.secret);
	load_pinned_signer_pubkey(&pinned_signer);

	/* Split "host:port" on the LAST colon (so bracketless IPv6 literals
	 * still misparse loudly rather than silently; use host:port for demo). */
	colon = strrchr(addr, ':');
	if (!colon || colon == addr)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "SEQLN_SIGNER_ADDR must be host:port, got '%s'",
			      addr);
	host = tal_strndup(tmpctx, addr, colon - addr);
	port = tal_strdup(tmpctx, colon + 1);

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	gai = getaddrinfo(host, port, &hints, &res);
	if (gai != 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "remote signer resolve %s:%s: %s",
			      host, port, gai_strerror(gai));

	for (ai = res; ai; ai = ai->ai_next) {
		fd = socket(ai->ai_family, ai->ai_socktype, ai->ai_protocol);
		if (fd < 0)
			continue;
		if (connect(fd, ai->ai_addr, ai->ai_addrlen) == 0)
			break;
		close(fd);
		fd = -1;
	}
	freeaddrinfo(res);

	if (fd < 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "remote signer connect %s:%s failed: %s",
			      host, port, strerror(errno));

	/* Low latency for the synchronous per-sign round-trips. */
	setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));

	/* Run the Noise_XK initiator handshake.  On success we have an
	 * encrypted, mutually-authenticated channel; on failure (wrong/absent
	 * device key, tampering, I/O) we abort — the node will not boot. */
	signer_noise = signer_noise_connect(NULL, fd, &my_priv.secret,
					    &pinned_signer);
	if (!signer_noise) {
		/* The noise channel owns `fd` and closed it already. */
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "remote signer %s:%s: Noise_XK handshake FAILED"
			      " (device did not present the pinned key, or"
			      " tampering) — refusing to run", host, port);
	}

	pubkey_from_privkey(&my_priv, &my_pub);
	status_unusual("hsmd-proxy: SECURED (BOLT-8 Noise_XK, mutual-auth) to"
		       " REMOTE signer at %s:%s; my static pubkey %s, pinned"
		       " device %s", host, port,
		       fmt_pubkey(tmpctx, &my_pub),
		       fmt_pubkey(tmpctx, &pinned_signer));
}

/*~ Remember a state-establishing request so a reconnecting device can be
 * re-primed with it.  We tal-dup the raw message off `prime_ctx` (long-lived);
 * `msg_in` itself is the client's transient buffer and must not be retained. */
static struct primed_req *new_primed_req(const tal_t *ctx, bool is_main,
					 const struct node_id *id, u64 dbid,
					 u64 capabilities, const u8 *msg_in)
{
	struct primed_req *p = tal(ctx, struct primed_req);
	p->is_main = is_main;
	p->id = *id;
	p->dbid = dbid;
	p->capabilities = capabilities;
	p->msg = tal_dup_talarr(p, u8, msg_in);
	return p;
}

/*~ Called on the way through forward_to_signer (LISTEN mode only), after a
 * request was ACCEPTED by the device, to cache the ones a reconnecting device
 * would need replayed: the (single) INIT and the latest SETUP_CHANNEL per
 * channel; FORGET_CHANNEL drops a channel's cache. */
static void remember_priming(bool is_main, const struct node_id *id, u64 dbid,
			     u64 capabilities, enum hsmd_wire reqt,
			     const u8 *msg_in, const u8 *reply)
{
	struct primed_req *old;

	switch (reqt) {
	case WIRE_HSMD_INIT:
		tal_free(primed_init);
		tal_free(primed_init_reply);
		primed_init = new_primed_req(prime_ctx, is_main, id, dbid,
					     capabilities, msg_in);
		primed_init_reply = tal_dup_talarr(prime_ctx, u8, reply);
		break;
	case WIRE_HSMD_SETUP_CHANNEL:
		old = uintmap_get(&primed_setup, dbid);
		if (old) {
			uintmap_del(&primed_setup, dbid);
			tal_free(old);
		}
		uintmap_add(&primed_setup, dbid,
			    new_primed_req(prime_ctx, is_main, id, dbid,
					   capabilities, msg_in));
		break;
	case WIRE_HSMD_FORGET_CHANNEL:
		old = uintmap_get(&primed_setup, dbid);
		if (old) {
			uintmap_del(&primed_setup, dbid);
			tal_free(old);
		}
		break;
	default:
		break;
	}
}

/*~ Replay one cached priming request to the (freshly reconnected) device and
 * discard the reply.  Returns false if the device dropped again mid-replay (so
 * the caller re-accepts), or — for INIT — if the reply DIFFERS from the one the
 * original device gave: that means a different node secret behind the pinned
 * transport key, which we refuse (fail-closed identity guard). */
static bool replay_priming(const struct primed_req *p, const u8 *expect_reply)
{
	u8 *reply;

	if (!signer_noise_write_request(signer_noise, p->is_main, &p->id,
					p->dbid, p->capabilities, p->msg))
		return false;
	reply = signer_noise_read_reply(tmpctx, signer_noise);
	if (!reply)
		return false;

	if (expect_reply
	    && (tal_bytelen(reply) != tal_bytelen(expect_reply)
		|| memcmp(reply, expect_reply, tal_bytelen(reply)) != 0)) {
		status_broken("hsmd-proxy: reconnected device INIT reply MISMATCH"
			      " — a different node identity behind the pinned"
			      " transport key; refusing this device");
		return false;
	}
	return true;
}

/*~ Re-establish the device's in-memory session state after a fresh handshake:
 * replay INIT, then every live channel's SETUP_CHANNEL.  Returns false if the
 * device dropped (or failed the INIT identity guard) so the caller re-accepts;
 * true once the device is ready to serve live requests again. */
static bool prime_device(void)
{
	struct primed_req *p;
	u64 dbid;

	/* Device dropped before it was ever INIT'd: nothing to replay; the live
	 * request that follows (the INIT itself) will prime it. */
	if (!primed_init)
		return true;

	if (!replay_priming(primed_init, primed_init_reply))
		return false;

	for (p = uintmap_first(&primed_setup, &dbid); p;
	     p = uintmap_after(&primed_setup, &dbid)) {
		if (!replay_priming(p, NULL))
			return false;
	}

	status_unusual("hsmd-proxy: reconnected device re-primed (INIT +"
		       " tracked channels); resuming service");
	return true;
}

/*~ Block on the LISTEN socket until an authenticated device connects, running a
 * FRESH Noise_XK responder handshake (new ephemeral keys) against the SAME
 * pinned device static key.  A connector that fails the handshake (wrong key /
 * no handshake / tampering) is rejected — its fd is closed by the noise channel
 * destructor — and we keep listening (fail-closed).  Sets `signer_noise`. */
static void accept_one_device(void)
{
	int cfd, one = 1;

	for (;;) {
		cfd = accept(signer_listen_fd, NULL, NULL);
		if (cfd < 0) {
			if (errno == EINTR)
				continue;
			status_failed(STATUS_FAIL_INTERNAL_ERROR,
				      "signer listen accept failed: %s",
				      strerror(errno));
		}
		setsockopt(cfd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
		signer_noise = signer_noise_accept(NULL, cfd,
						   &signer_listen_priv,
						   &signer_listen_pinned);
		if (signer_noise) {
			status_unusual("hsmd-proxy: device signer AUTHENTICATED"
				       " (Noise_XK responder); serving");
			return;
		}
		/* Rejected: the noise channel already closed `cfd`. */
		status_unusual("hsmd-proxy: REJECTED a connector (Noise_XK"
			       " handshake failed / not the pinned device key);"
			       " still listening");
	}
}

/*~ LISTEN mode reconnect: accept a fresh device and re-prime it, retrying if it
 * drops mid-priming, until we have a device ready to serve.  On return
 * `signer_noise` is a live, primed secure channel. */
static void reconnect_device(void)
{
	for (;;) {
		accept_one_device();
		if (prime_device())
			return;
		status_unusual("hsmd-proxy: device dropped/refused during session"
			       " priming; awaiting another device");
		signer_noise = tal_free(signer_noise);
	}
}

/*~ SeqLN Tier-2 BROWSER topology (the role flip).  A browser device signer
 * cannot listen() for an inbound connection, so it connects OUT and plays the
 * Noise INITIATOR; the hosted proxy therefore BINDS a TCP listener, accepts a
 * device connection, and runs the Noise_XK RESPONDER over it.  The resulting
 * SECURED channel is used as the signer link exactly like the connect() path.
 *
 * RECONNECTABLE: a browser device can disconnect (tab close/reopen, network
 * blip) and come back.  We therefore keep the listen socket open for the whole
 * lifetime of the proxy; when the current device drops, forward_to_signer loops
 * back through reconnect_device() to accept + re-authenticate + re-prime a fresh
 * device WITHOUT restarting the node or dropping lightningd's fd-3.
 *
 * Same fail-closed contract + same pinned keys as connect mode (SEQLN_HOST_PRIVKEY
 * = the proxy's own static priv, SEQLN_SIGNER_PEER_PUBKEY = the pinned device
 * pubkey); a connector that does not present the pinned key is REJECTED at the
 * handshake and served zero frames, and we keep listening for the real device.
 * contrib/seqln-signer/src/noise.rs's `Initiator` is the byte-compatible peer.
 */
static void listen_remote_signer(const char *addr)
{
	char *host, *port, *colon;
	struct addrinfo hints, *res, *ai;
	struct privkey my_priv;
	struct pubkey my_pub;
	int lfd = -1, gai, one = 1;

	/* Load + validate the pinned keys BEFORE we touch the network, and keep
	 * them (plus the listen fd) for the lifetime of the proxy so we can
	 * re-accept a reconnecting device later. */
	load_host_privkey(&signer_listen_priv);
	load_pinned_signer_pubkey(&signer_listen_pinned);
	my_priv.secret = signer_listen_priv;
	pubkey_from_privkey(&my_priv, &my_pub);

	colon = strrchr(addr, ':');
	if (!colon || colon == addr)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "SEQLN_SIGNER_LISTEN must be host:port, got '%s'",
			      addr);
	host = tal_strndup(tmpctx, addr, colon - addr);
	port = tal_strdup(tmpctx, colon + 1);

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;
	gai = getaddrinfo(host[0] ? host : NULL, port, &hints, &res);
	if (gai != 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "signer listen resolve %s:%s: %s",
			      host, port, gai_strerror(gai));

	for (ai = res; ai; ai = ai->ai_next) {
		lfd = socket(ai->ai_family, ai->ai_socktype, ai->ai_protocol);
		if (lfd < 0)
			continue;
		setsockopt(lfd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
		/* backlog > 1: tolerate a reconnect racing the old fd's close. */
		if (bind(lfd, ai->ai_addr, ai->ai_addrlen) == 0
		    && listen(lfd, 5) == 0)
			break;
		close(lfd);
		lfd = -1;
	}
	freeaddrinfo(res);
	if (lfd < 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "signer listen bind %s:%s failed: %s",
			      host, port, strerror(errno));

	/* Latch reconnect mode + keep the listen socket open for our lifetime. */
	signer_listen_fd = lfd;
	signer_listen_mode = true;

	status_unusual("hsmd-proxy: LISTENING (BOLT-8 Noise_XK RESPONDER,"
		       " mutual-auth) on %s:%s for the device signer; my static"
		       " pubkey %s, pinned device %s; reconnect-tolerant",
		       host, port, fmt_pubkey(tmpctx, &my_pub),
		       fmt_pubkey(tmpctx, &signer_listen_pinned));

	/* Bring up the first device (blocks until one authenticates).  Nothing
	 * is cached yet, so prime_device() is a no-op; the incoming INIT primes. */
	accept_one_device();
}

/*~ Forward one request to signerd and relay its reply to the client.  This is
 * the drop-in replacement for the monolithic hsmd's
 * `req_reply(..., hsmd_handle_client_message(...))`.  It is a synchronous
 * round-trip; the whole hsmd protocol is request/response so blocking the io
 * loop here is exactly the monolithic behaviour. */
/*~ LISTEN mode round-trip: write the request + read the reply over the secure
 * device channel, transparently surviving a device disconnect.  If the device
 * drops (write or read fails / EOF), we close the dead channel and block in
 * reconnect_device() until a fresh device authenticates and is re-primed, then
 * RETRY the same request — so no lightningd request is lost and fd-3 is never
 * touched.  Always returns a non-NULL reply (a zero-length array is the device's
 * error sentinel, handled by the caller). */
static u8 *listen_roundtrip(const tal_t *ctx, bool is_main,
			    const struct node_id *id, u64 dbid,
			    u64 capabilities, const u8 *msg_in,
			    enum hsmd_wire reqt)
{
	for (;;) {
		u8 *reply;

		if (!signer_noise)
			reconnect_device();

		if (!signer_noise_write_request(signer_noise, is_main, id, dbid,
						capabilities, msg_in)) {
			status_unusual("hsmd-proxy: device link WRITE failed on"
				       " %s; device disconnected, awaiting"
				       " reconnect", hsmd_wire_name(reqt));
			signer_noise = tal_free(signer_noise);
			continue;
		}
		reply = signer_noise_read_reply(ctx, signer_noise);
		if (!reply) {
			status_unusual("hsmd-proxy: device link READ failed on"
				       " %s; device disconnected, awaiting"
				       " reconnect", hsmd_wire_name(reqt));
			signer_noise = tal_free(signer_noise);
			continue;
		}
		return reply;
	}
}

static struct io_plan *forward_to_signer(struct io_conn *conn,
					 struct client *c,
					 const u8 *msg_in)
{
	bool is_main = (c->dbid == 0);
	enum hsmd_wire reqt = fromwire_peektype(msg_in);
	u8 *reply;

	/* Three transports:
	 *  - LISTEN (browser) mode: Noise-secured + reconnect-tolerant.
	 *  - ADDR (connect) mode: Noise-secured, single-shot (unchanged).
	 *  - local fork mode: raw framed write over the trusted socketpair fd. */
	if (signer_listen_mode) {
		reply = listen_roundtrip(tmpctx, is_main, &c->id, c->dbid,
					 c->capabilities, msg_in, reqt);
	} else if (signer_noise) {
		if (!signer_noise_write_request(signer_noise, is_main, &c->id,
						c->dbid, c->capabilities,
						msg_in))
			status_failed(STATUS_FAIL_INTERNAL_ERROR,
				      "secure signer write (%s) failed",
				      hsmd_wire_name(reqt));
		reply = signer_noise_read_reply(tmpctx, signer_noise);
	} else {
		if (!signer_write_request(signer_fd, is_main, &c->id, c->dbid,
					  c->capabilities, msg_in))
			status_failed(STATUS_FAIL_INTERNAL_ERROR,
				      "signerd write (%s) failed: %s",
				      hsmd_wire_name(reqt), strerror(errno));
		reply = signer_read_reply(tmpctx, signer_fd);
	}
	if (!reply)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "signerd closed connection on %s",
			      hsmd_wire_name(reqt));

	/* Zero-length reply is signerd's error sentinel. */
	if (tal_bytelen(reply) == 0)
		return bad_req_fmt(conn, c, msg_in,
				   "signerd rejected request %s",
				   hsmd_wire_name(reqt));

	/* LISTEN mode: cache the state-establishing requests so a reconnecting
	 * device can be re-primed to serve this client again. */
	if (signer_listen_mode)
		remember_priming(is_main, &c->id, c->dbid, c->capabilities,
				 reqt, msg_in, reply);

	status_debug("hsmd-proxy: %s (dbid=%"PRIu64") -> signerd -> %s",
		     hsmd_wire_name(reqt), c->dbid,
		     hsmd_wire_name(fromwire_peektype(reply)));

	return req_reply(conn, c, take(reply));
}

/*~ We have a pre-init call in developer mode, to set dev flags */
static struct io_plan *preinit_hsm(struct io_conn *conn,
				   struct client *c,
				   const u8 *msg_in)
{
	struct tlv_hsmd_dev_preinit_tlvs *tlv;
	assert(developer);

	if (!fromwire_hsmd_dev_preinit(tmpctx, msg_in, &tlv))
		return bad_req(conn, c, msg_in);

	if (tlv->fail_preapprove)
		dev_fail_preapprove = *tlv->fail_preapprove;

	if (tlv->no_preapprove_check)
		dev_no_preapprove_check = *tlv->no_preapprove_check;

	if (tlv->warn_on_overgrind)
		dev_warn_on_overgrind = *tlv->warn_on_overgrind;

	status_debug("preinit: dev_fail_preapprove = %u, dev_no_preapprove_check = %u, dev_warn_on_overgrind = %u",
		     dev_fail_preapprove, dev_no_preapprove_check, dev_warn_on_overgrind);
	/* We don't send a reply, just read next */
	return client_read_next(conn, c);
}

/*~ Since we process requests then service them in strict order, and because
 * only lightningd can request a new client fd, we can get away with a global
 * here!  But because we are being tricky, I set it to an invalid value when
 * not in use, and sprinkle assertions around. */
static int pending_client_fd = -1;

/*~ This is the callback from below: having sent the reply, we now send the
 * fd for the client end of the new socketpair. */
static struct io_plan *send_pending_client_fd(struct io_conn *conn,
					      struct client *master)
{
	int fd = pending_client_fd;
	/* This must be the master. */
	assert(is_lightningd(master));
	assert(fd != -1);

	/* This sanity check shouldn't be necessary, but it's cheap. */
	pending_client_fd = -1;

	/*~There's arcane UNIX magic to send an open file descriptor over a
	 * UNIX domain socket.  There's no great way to autogenerate this
	 * though; especially for the receive side, so we always pass these
	 * manually immediately following the message.
	 *
	 * io_send_fd()'s third parameter is whether to close the local one
	 * after sending; that saves us YA callback.
	 */
	return io_send_fd(conn, fd, true, client_read_next, master);
}

/*~ This is used by the master to create a new client connection (which
 * becomes the HSM_FD for the subdaemon after forking). */
static struct io_plan *pass_client_hsmfd(struct io_conn *conn,
					 struct client *c,
					 const u8 *msg_in)
{
	int fds[2];
	u64 dbid, capabilities;
	struct node_id id;

	/* This must be lightningd itself. */
	assert(is_lightningd(c));

	if (!fromwire_hsmd_client_hsmfd(msg_in, &id, &dbid, &capabilities))
		return bad_req(conn, c, msg_in);

	/* socketpair is a bi-directional pipe, which is what we want. */
	if (socketpair(AF_UNIX, SOCK_STREAM, 0, fds) != 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR, "creating fds: %s",
			      strerror(errno));

	status_debug("new_client: %"PRIu64, dbid);
	new_client(c, c->chainparams, &id, dbid, capabilities, fds[0]);

	/*~ We stash this in a global, because we need to get both the fd and
	 * the client pointer to the callback.  The other way would be to
	 * create a boutique structure and hand that, but we don't need to. */
	pending_client_fd = fds[1];
	return io_write_wire(conn, take(towire_hsmd_client_hsmfd_reply(NULL)),
			     send_pending_client_fd, c);
}

static struct io_plan *handle_memleak(struct io_conn *conn,
				      struct client *c,
				      const u8 *msg_in)
{
	struct htable *memtable;
	bool found_leak;
	u8 *reply;

	memtable = memleak_start(tmpctx);
	memleak_ptr(memtable, msg_in);

	/* Now note clients and anything they point to. */
	memleak_scan_region(memtable, dbid_zero_clients, sizeof(dbid_zero_clients));
	memleak_scan_uintmap(memtable, &clients);
	memleak_scan_obj(memtable, status_conn);

	/* The LISTEN-mode reconnect priming cache is intentionally retained. */
	if (prime_ctx)
		memleak_scan_obj(memtable, prime_ctx);
	memleak_scan_uintmap(memtable, &primed_setup);

	memleak_ptr(memtable, dev_force_privkey);
	memleak_ptr(memtable, dev_force_bip32_seed);

	found_leak = dump_memleak(memtable, memleak_status_broken, NULL);
	reply = towire_hsmd_dev_memleak_reply(NULL, found_leak);
	return req_reply(conn, c, take(reply));
}

u8 *hsmd_status_bad_request(struct hsmd_client *client, const u8 *msg, const char *error)
{
	/* Extract the pointer to the hsmd representation of the
	 * client which has access to the underlying connection. */
	struct client *c = (struct client*)client->extra;
	bad_req_fmt(c->conn, c, msg, "%s", error);

	/* We often use `return hsmd_status_bad_request` to drop out, and NULL
	 * means we encountered an error. */
	return NULL;
}

void hsmd_status_fmt(enum log_level level, const struct node_id *peer,
		     const char *fmt, ...)
{
	va_list ap;

	va_start(ap, fmt);
	status_vfmt(level, peer, fmt, ap);
	va_end(ap);
}

void hsmd_status_failed(enum status_failreason reason, const char *fmt, ...)
{
	va_list ap;
	char *str;

	va_start(ap, fmt);
	str = tal_vfmt(NULL, fmt, ap);
	va_end(ap);

	/* Give a nice backtrace when this happens! */
	if (reason == STATUS_FAIL_INTERNAL_ERROR)
		send_backtrace(str);

	status_send_fatal(take(towire_status_fail(NULL, reason, str)));
}

/*~ This is the core of the HSM daemon: handling requests. */
static struct io_plan *handle_client(struct io_conn *conn, struct client *c)
{
	enum hsmd_wire t = fromwire_peektype(c->msg_in);

	if (!is_lightningd(c))
		status_peer_debug(&c->id, "Got %s", hsmd_wire_name(t));

	/* Before we do anything else, is this client allowed to do
	 * what he asks for? */
	if (!hsmd_check_client_capabilities(c->hsmd_client, t))
		return bad_req_fmt(conn, c, c->msg_in,
				   "client does not have capability to run %d",
				   t);

	/* Now actually go and do what the client asked for */
	switch (t) {
	case WIRE_HSMD_DEV_PREINIT:
		/* Dev-only: keep local (sets this process's libhsmd dev flags).
		 * The dev-forced-key flags are not plumbed to signerd in M1;
		 * we don't run the split node in developer mode. */
		return preinit_hsm(conn, c, c->msg_in);

	case WIRE_HSMD_CLIENT_HSMFD:
		/* LOAD-BEARING: fd multiplexing stays local (SCM_RIGHTS). */
		return pass_client_hsmfd(conn, c, c->msg_in);

	case WIRE_HSMD_DEV_MEMLEAK:
		if (!developer)
			break;
		return handle_memleak(conn, c, c->msg_in);

	/* Everything below needs the root secret, so it is forwarded to the
	 * out-of-process signerd (init + bip86 check included: signerd owns the
	 * secret and special-cases them, mirroring the monolithic hsmd). */
	case WIRE_HSMD_INIT:
	case WIRE_HSMD_CHECK_BIP86_PUBKEY:
	case WIRE_HSMD_NEW_CHANNEL:
	case WIRE_HSMD_SETUP_CHANNEL:
 	case WIRE_HSMD_CHECK_OUTPOINT:
 	case WIRE_HSMD_LOCK_OUTPOINT:
 	case WIRE_HSMD_FORGET_CHANNEL:
	case WIRE_HSMD_SIGN_COMMITMENT_TX:
	case WIRE_HSMD_VALIDATE_COMMITMENT_TX:
	case WIRE_HSMD_REVOKE_COMMITMENT_TX:
	case WIRE_HSMD_VALIDATE_REVOCATION:
	case WIRE_HSMD_SIGN_PENALTY_TO_US:
	case WIRE_HSMD_SIGN_REMOTE_COMMITMENT_TX:
	case WIRE_HSMD_SIGN_REMOTE_HTLC_TX:
	case WIRE_HSMD_SIGN_MUTUAL_CLOSE_TX:
	case WIRE_HSMD_SIGN_SPLICE_TX:
	case WIRE_HSMD_GET_PER_COMMITMENT_POINT:
	case WIRE_HSMD_SIGN_WITHDRAWAL:
	case WIRE_HSMD_GET_CHANNEL_BASEPOINTS:
	case WIRE_HSMD_SIGN_INVOICE:
	case WIRE_HSMD_SIGN_MESSAGE:
	case WIRE_HSMD_BIP137_SIGN_MESSAGE:
	case WIRE_HSMD_SIGN_OPTION_WILL_FUND_OFFER:
	case WIRE_HSMD_SIGN_BOLT12:
	case WIRE_HSMD_SIGN_BOLT12_2:
	case WIRE_HSMD_PREAPPROVE_INVOICE:
	case WIRE_HSMD_PREAPPROVE_KEYSEND:
	case WIRE_HSMD_PREAPPROVE_INVOICE_CHECK:
	case WIRE_HSMD_PREAPPROVE_KEYSEND_CHECK:
	case WIRE_HSMD_ECDH_REQ:
	case WIRE_HSMD_CHECK_FUTURE_SECRET:
	case WIRE_HSMD_GET_OUTPUT_SCRIPTPUBKEY:
	case WIRE_HSMD_DERIVE_SECRET:
	case WIRE_HSMD_CANNOUNCEMENT_SIG_REQ:
	case WIRE_HSMD_SIGN_ANY_CANNOUNCEMENT_REQ:
	case WIRE_HSMD_NODE_ANNOUNCEMENT_SIG_REQ:
	case WIRE_HSMD_CUPDATE_SIG_REQ:
	case WIRE_HSMD_SIGN_REMOTE_HTLC_TO_US:
	case WIRE_HSMD_SIGN_DELAYED_PAYMENT_TO_US:
	case WIRE_HSMD_CHECK_PUBKEY:
	case WIRE_HSMD_SIGN_ANY_PENALTY_TO_US:
	case WIRE_HSMD_SIGN_ANY_DELAYED_PAYMENT_TO_US:
	case WIRE_HSMD_SIGN_ANY_REMOTE_HTLC_TO_US:
	case WIRE_HSMD_SIGN_ANY_LOCAL_HTLC_TX:
	case WIRE_HSMD_SIGN_ANCHORSPEND:
	case WIRE_HSMD_SIGN_HTLC_TX_MINGLE:
		/* Forward to the out-of-process signer. */
		return forward_to_signer(conn, c, c->msg_in);

	case WIRE_HSMD_ECDH_RESP:
	case WIRE_HSMD_CANNOUNCEMENT_SIG_REPLY:
	case WIRE_HSMD_CUPDATE_SIG_REPLY:
	case WIRE_HSMD_CLIENT_HSMFD_REPLY:
	case WIRE_HSMD_NEW_CHANNEL_REPLY:
	case WIRE_HSMD_SETUP_CHANNEL_REPLY:
	case WIRE_HSMD_CHECK_OUTPOINT_REPLY:
	case WIRE_HSMD_LOCK_OUTPOINT_REPLY:
 	case WIRE_HSMD_FORGET_CHANNEL_REPLY:
	case WIRE_HSMD_NODE_ANNOUNCEMENT_SIG_REPLY:
	case WIRE_HSMD_SIGN_WITHDRAWAL_REPLY:
	case WIRE_HSMD_SIGN_INVOICE_REPLY:
	case WIRE_HSMD_INIT_REPLY_V4:
	case WIRE_HSMD_INIT_REPLY_FAILURE:
	case WIRE_HSMD_DERIVE_SECRET_REPLY:
	case WIRE_HSMSTATUS_CLIENT_BAD_REQUEST:
	case WIRE_HSMD_SIGN_COMMITMENT_TX_REPLY:
	case WIRE_HSMD_VALIDATE_COMMITMENT_TX_REPLY:
	case WIRE_HSMD_REVOKE_COMMITMENT_TX_REPLY:
	case WIRE_HSMD_VALIDATE_REVOCATION_REPLY:
	case WIRE_HSMD_SIGN_TX_REPLY:
	case WIRE_HSMD_SIGN_OPTION_WILL_FUND_OFFER_REPLY:
	case WIRE_HSMD_GET_PER_COMMITMENT_POINT_REPLY:
	case WIRE_HSMD_CHECK_FUTURE_SECRET_REPLY:
	case WIRE_HSMD_GET_CHANNEL_BASEPOINTS_REPLY:
	case WIRE_HSMD_DEV_MEMLEAK_REPLY:
	case WIRE_HSMD_SIGN_MESSAGE_REPLY:
	case WIRE_HSMD_BIP137_SIGN_MESSAGE_REPLY:
	case WIRE_HSMD_GET_OUTPUT_SCRIPTPUBKEY_REPLY:
	case WIRE_HSMD_SIGN_BOLT12_REPLY:
	case WIRE_HSMD_SIGN_BOLT12_2_REPLY:
	case WIRE_HSMD_PREAPPROVE_INVOICE_REPLY:
	case WIRE_HSMD_PREAPPROVE_KEYSEND_REPLY:
	case WIRE_HSMD_PREAPPROVE_INVOICE_CHECK_REPLY:
	case WIRE_HSMD_PREAPPROVE_KEYSEND_CHECK_REPLY:
	case WIRE_HSMD_CHECK_PUBKEY_REPLY:
	case WIRE_HSMD_CHECK_BIP86_PUBKEY_REPLY:
	case WIRE_HSMD_SIGN_ANCHORSPEND_REPLY:
	case WIRE_HSMD_SIGN_HTLC_TX_MINGLE_REPLY:
	case WIRE_HSMD_SIGN_ANY_CANNOUNCEMENT_REPLY:
		return bad_req_fmt(conn, c, c->msg_in,
				   "Received an incoming message of type %s, "
				   "which is not a request",
				   hsmd_wire_name(t));
	}

	return bad_req_fmt(conn, c, c->msg_in, "Unknown request");
}

static void master_gone(struct io_conn *unused UNUSED, struct client *c UNUSED)
{
	daemon_shutdown();
	/* Can't tell master, it's gone. */
	exit(2);
}

/*~ SeqLN EVICT-ON-CONNECT (LISTEN/browser mode only).
 *
 * The request-driven reconnect path (listen_roundtrip) only notices a dropped
 * device when lightningd next makes an HSM request.  So if the LSP restarts (or a
 * tab closes) while lightningd is IDLE, the proxy keeps holding the now-severed
 * device as its "active" signer, and a FRESH browser signer connecting on the
 * listen socket is never accept()ed — it sticks at the handshake forever until a
 * full proxy revive.
 *
 * This periodic tick closes that gap: a NON-BLOCKING poll of the listen socket,
 * and if a newcomer is pending we accept + Noise-authenticate it.  If it presents
 * the pinned device key we EVICT the current signer and install + re-prime the
 * newcomer — "newest device wins" — so a reconnect always replaces a stale one
 * without a manual revive.  A connector that fails the pinned-key handshake is
 * rejected and the current signer is left untouched (fail-closed, same contract
 * as accept_one_device).  The tick only fires when the io_loop is idle (never
 * mid-request, since listen_roundtrip's device I/O is blocking), so it never
 * interrupts an in-flight signing round-trip. */
#define SEQLN_EVICT_TICK_MS 1000
static void evict_on_connect_tick(struct timers *timers)
{
	struct pollfd pfd = { .fd = signer_listen_fd, .events = POLLIN, .revents = 0 };

	while (signer_listen_fd >= 0
	       && poll(&pfd, 1, 0) > 0 && (pfd.revents & POLLIN)) {
		int one = 1, cfd = accept(signer_listen_fd, NULL, NULL);
		struct signer_noise *newn;

		pfd.revents = 0;
		if (cfd < 0)
			break;
		setsockopt(cfd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
		newn = signer_noise_accept(NULL, cfd, &signer_listen_priv,
					   &signer_listen_pinned);
		if (!newn) {
			/* Rejected (wrong key / bad handshake); the noise channel
			 * already closed cfd.  Keep the current signer. */
			status_unusual("hsmd-proxy: evict-on-connect REJECTED a"
				       " connector (not the pinned device); keeping"
				       " the current signer");
			continue;
		}
		status_unusual("hsmd-proxy: evict-on-connect: newcomer"
			       " AUTHENTICATED; evicting the previous signer and"
			       " re-priming the newcomer (newest wins)");
		tal_free(signer_noise);
		signer_noise = newn;
		if (!prime_device()) {
			status_unusual("hsmd-proxy: evict-on-connect: newcomer"
				       " dropped during priming; awaiting another");
			signer_noise = tal_free(signer_noise);
		}
	}

	/* Re-arm. */
	new_reltimer(timers, NULL, time_from_msec(SEQLN_EVICT_TICK_MS),
		     evict_on_connect_tick, timers);
}

int main(int argc, char *argv[])
{
	struct client *master;

	setup_locale();

	/* This sets up tmpctx, various --developer options, backtraces, etc. */
	developer = subdaemon_setup(argc, argv);

	/* A trivial daemon_conn just for writing. */
	status_conn = daemon_conn_new(NULL, STDIN_FILENO, NULL, NULL, NULL);
	status_setup_async(status_conn);
	uintmap_init(&clients);
	uintmap_init(&primed_setup);
	/* Long-lived home for the LISTEN-mode reconnect priming cache. */
	prime_ctx = tal(NULL, char);

	/*~ Bring up the signer before we start serving lightningd, so it is
	 * ready for the very first request (WIRE_HSMD_INIT).  Three transports:
	 *  - SEQLN_SIGNER_LISTEN="host:port" set => BIND + accept ONE inbound
	 *    device connection and run the Noise_XK RESPONDER (the BROWSER
	 *    topology: the device can't listen, so it connects OUT to us).
	 *  - else SEQLN_SIGNER_ADDR="host:port" => connect() OUT to a REMOTE
	 *    signer over TCP as the Noise INITIATOR (the phone/desktop topology).
	 *  - otherwise (default) => fork+exec a LOCAL signerd (trusted socket). */
	{
		const char *listen_addr = getenv("SEQLN_SIGNER_LISTEN");
		const char *remote_addr = getenv("SEQLN_SIGNER_ADDR");
		if (listen_addr && listen_addr[0] != '\0')
			listen_remote_signer(listen_addr);
		else if (remote_addr && remote_addr[0] != '\0')
			connect_remote_signer(remote_addr);
		else
			start_signerd(argv[0]);
	}

	master = new_client(NULL, NULL, NULL, 0,
			    HSM_PERM_MASTER | HSM_PERM_SIGN_GOSSIP | HSM_PERM_ECDH,
			    REQ_FD);

	/* First client == lightningd. */
	assert(is_lightningd(master));

	/* When conn closes, everything is freed. */
	io_set_finish(master->conn, master_gone, master);

	/*~ In LISTEN (browser) mode we drive a short recurring timer so a
	 * reconnecting device is accepted promptly even while lightningd is idle
	 * (evict-on-connect, above).  io_loop returns on each timer expiry; we run
	 * the timer's callback (which re-arms) and loop.  master_gone exit(2)s on
	 * shutdown, so this loop never needs to terminate on its own.  Other
	 * transports have no listen socket, so they keep the original timer-less
	 * loop unchanged. */
	if (signer_listen_mode) {
		struct timers timers;
		timers_init(&timers, time_mono());
		new_reltimer(&timers, NULL,
			     time_from_msec(SEQLN_EVICT_TICK_MS),
			     evict_on_connect_tick, &timers);
		for (;;) {
			struct timer *expired;
			io_loop(&timers, &expired);
			timer_expired(expired);
		}
	}

	/*~ The two NULL args are a list of timers, and the timer which expired:
	 * we don't have any timers. */
	io_loop(NULL, NULL);

	/*~ This should never be reached: io_loop only exits on io_break which
	 * we don't call, a timer expiry which we don't have, or all connections
	 * being closed, and closing the master calls master_gone. */
	abort();
}

/*~ Congratulations on making it through the first of the seven dwarves!
 * (And Christian wondered why I'm so fond of having separate daemons!).
 *
 * We continue our story in the next-more-complex daemon: connectd/connectd.c
 */
