/*~ Welcome to the hsm PROXY daemon (SeqLN Tier-2, milestone M1)!
 *
 * This is a MODIFIED COPY of hsmd/hsmd.c.  It keeps ALL of the ccan/io + fd
 * machinery, the per-subdaemon fd multiplexing (WIRE_HSMD_CLIENT_HSMFD via
 * socketpair + SCM_RIGHTS), the client bookkeeping and the capability checks,
 * so from lightningd's point of view it IS the hsmd (fd 3 speaks the hsmd wire).
 *
 * The one thing it does NOT do is keep the root secret or run libhsmd's crypto:
 * it holds no hsm_secret and never calls hsmd_init / hsmd_handle_client_message.
 * Instead it fork/exec's a separate `signerd` process (hsmd/signerd.c) sharing
 * our working directory, and for every request that needs the secret it forwards
 * a framed {client_ctx, hsmd_msg} to signerd (see hsmd/signer_frame.h) and
 * relays signerd's reply back to the client.  fd multiplexing stays 100% local
 * here, exactly as the Tier-2 design requires.
 *
 * We still link libhsmd, but only for the pure `hsmd_check_client_capabilities`
 * helper (and the dev flag globals); no secret is ever loaded in this process.
 */
#include "config.h"
#include <ccan/array_size/array_size.h>
#include <ccan/intmap/intmap.h>
#include <ccan/io/fdpass/fdpass.h>
#include <ccan/noerr/noerr.h>
#include <ccan/read_write_all/read_write_all.h>
#include <ccan/tal/path/path.h>
#include <ccan/tal/str/str.h>
#include <common/daemon_conn.h>
#include <common/memleak.h>
#include <common/status.h>
#include <common/status_wiregen.h>
#include <common/subdaemon.h>
#include <common/utils.h>
#include <errno.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
/*~ _wiregen files are autogenerated by tools/generate-wire.py */
#include <hsmd/libhsmd.h>
#include <hsmd/permissions.h>
#include <hsmd/signer_frame.h>
#include <wire/wire_io.h>
#include <wire/wire_sync.h>

/*~ Each subdaemon is started with stdin connected to lightningd (for status
 * messages), and stderr untouched (for emergency printing).  File descriptors
 * 3 and beyond are set up on other sockets: for hsmd, fd 3 is the request
 * stream from lightningd. */
#define REQ_FD 3

/*~ The single transport to our out-of-process signerd (set up in main before
 * the io_loop).  All secret-bearing requests are forwarded over this fd. */
static int signer_fd = -1;

/*~ We keep track of clients, but there's not much to keep. */
struct client {
	/* The ccan/io async io connection for this client: it closes, we die. */
	struct io_conn *conn;

	/*~ io_read_wire needs a pointer to store incoming messages until
	 * it has the complete thing; this is it. */
	u8 *msg_in;

	/*~ Useful for logging, but also used to derive the per-channel seed. */
	struct node_id id;

	/*~ This is a unique value handed to us from lightningd, used for
	 * per-channel seed generation (a single id may have multiple channels
	 * over time).
	 *
	 * It's actually zero for the initial lightningd client connection and
	 * the ones for gossipd and connectd, which don't have channels
	 * associated. */
	u64 dbid;

	/* What is this client allowed to ask for? */
	u64 capabilities;

	/* Params to apply to all transactions for this client */
	const struct chainparams *chainparams;

	/* Client context to pass over to libhsmd for its calls. */
	struct hsmd_client *hsmd_client;
};

/*~ We keep a map of nonzero dbid -> clients, mainly for leak detection.
 * This is ccan/uintmap, which maps u64 to some (non-NULL) pointer.
 * I really dislike these kinds of declaration-via-magic macro things, as
 * tags can't find them without special hacks, but the payoff here is that
 * the map is typesafe: the compiler won't let you put anything in but a
 * struct client pointer. */
static UINTMAP(struct client *) clients;
/*~ Plus the three zero-dbid clients: master, gossipd and connnectd. */
static struct client *dbid_zero_clients[3];
static size_t num_dbid_zero_clients;

/* Are we in developer mode */
static bool developer;

/*~ We need this deep inside bad_req_fmt, and for memleak, so we make it a
 * global. */
static struct daemon_conn *status_conn;

/* This is used for various assertions and error cases. */
static bool is_lightningd(const struct client *client)
{
	return client == dbid_zero_clients[0];
}

/* Pre-declare this, due to mutual recursion */
static struct io_plan *handle_client(struct io_conn *conn, struct client *c);

/*~ ccan/compiler.h defines PRINTF_FMT as the gcc compiler hint so it will
 * check that fmt and other trailing arguments really are the correct type.
 *
 * This is a convenient helper to tell lightningd we've received a bad request
 * and closes the client connection.  This should never happen, of course, but
 * we definitely want to log if it does.
 */
static struct io_plan *bad_req_fmt(struct io_conn *conn,
				   struct client *c,
				   const u8 *msg_in,
				   const char *fmt, ...)
	PRINTF_FMT(4,5);

static struct io_plan *bad_req_fmt(struct io_conn *conn,
				   struct client *c,
				   const u8 *msg_in,
				   const char *fmt, ...)
{
	va_list ap;
	char *str;

	va_start(ap, fmt);
	str = tal_vfmt(tmpctx, fmt, ap);
	va_end(ap);

	/*~ If the client was actually lightningd, it's Game Over; we actually
	 * fail in this case, and it will too. */
	if (is_lightningd(c)) {
		status_broken("%s", str);
		master_badmsg(fromwire_peektype(msg_in), msg_in);
	}

	/*~ Nobody should give us bad requests; it's a sign something is broken */
	status_broken("%s: %s", fmt_node_id(tmpctx, &c->id), str);

	/*~ Note the use of NULL as the ctx arg to towire_hsmstatus_: only
	 * use NULL as the allocation when we're about to immediately free it
	 * or hand it off with take(), as here.  That makes it clear we don't
	 * expect it to linger, and in fact our memleak detection will
	 * complain if it does (unlike using the deliberately-transient
	 * tmpctx). */
	daemon_conn_send(status_conn,
			 take(towire_hsmstatus_client_bad_request(NULL,
								  &c->id,
								  str,
								  msg_in)));

	/*~ The way ccan/io works is that you return the "plan" for what to do
	 * next (eg. io_read).  io_close() is special: it means to close the
	 * connection. */
	return io_close(conn);
}

/* Convenience wrapper for when we simply can't parse. */
static struct io_plan *bad_req(struct io_conn *conn,
			       struct client *c,
			       const u8 *msg_in)
{
	return bad_req_fmt(conn, c, msg_in, "could not parse request");
}

/*~ This plan simply says: read the next packet into 'c->msg_in' (parent 'c'),
 * and then call handle_client with argument 'c' */
static struct io_plan *client_read_next(struct io_conn *conn, struct client *c)
{
	c->msg_in = tal_free(c->msg_in);
	return io_read_wire(conn, c, &c->msg_in, handle_client, c);
}

/*~ This is the destructor on our client: we may call it manually, but
 * generally it's called because the io_conn associated with the client is
 * closed by the other end. */
static void destroy_client(struct client *c)
{
	if (!uintmap_del(&clients, c->dbid))
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "Failed to remove client dbid %"PRIu64, c->dbid);
}

static struct client *new_client(const tal_t *ctx,
				 const struct chainparams *chainparams,
				 const struct node_id *id,
				 u64 dbid,
				 const u64 capabilities,
				 int fd)
{
	struct client *c = tal(ctx, struct client);

	c->msg_in = NULL;

	/*~ All-zero pubkey is used for the initial master connection */
	if (id) {
		c->id = *id;
		if (!node_id_valid(id))
			status_failed(STATUS_FAIL_INTERNAL_ERROR,
				      "Invalid node id %s",
				      fmt_node_id(tmpctx, id));
	} else {
		memset(&c->id, 0, sizeof(c->id));
	}
	c->dbid = dbid;

	c->capabilities = capabilities;
	c->chainparams = chainparams;

	/*~ This is the core of ccan/io: the connection creation calls a
	 * callback which returns the initial plan to execute: in our case,
	 * read a message.*/
	c->conn = io_new_conn(ctx, fd, client_read_next, c);

	/*~ tal_steal() moves a pointer to a new parent.  At this point, the
	 * hierarchy is:
	 *
	 *   ctx -> c
	 *   ctx -> c->conn
	 *
	 * We want to the c->conn to own 'c', so that if the io_conn closes,
	 * the client is freed:
	 *
	 *   ctx -> c->conn -> c.
	 */
	tal_steal(c->conn, c);

	/* We put the special zero-db HSM connections into an array, the rest
	 * go into the map. */
	if (dbid == 0) {
		assert(num_dbid_zero_clients < ARRAY_SIZE(dbid_zero_clients));
		dbid_zero_clients[num_dbid_zero_clients++] = c;
		c->hsmd_client = hsmd_client_new_main(c, c->capabilities, c);
	} else {
		struct client *old_client = uintmap_get(&clients, dbid);

		/* Close conn and free any old client of this dbid. */
		if (old_client)
			io_close(old_client->conn);

		if (!uintmap_add(&clients, dbid, c))
			status_failed(STATUS_FAIL_INTERNAL_ERROR,
				      "Failed inserting dbid %"PRIu64, dbid);
		tal_add_destructor(c, destroy_client);
		c->hsmd_client =
		    hsmd_client_new_peer(c, c->capabilities, dbid, id, c);
	}

	return c;
}

/* This is the common pattern for the tail of each handler in this file. */
static struct io_plan *req_reply(struct io_conn *conn,
				 struct client *c,
				 const u8 *msg_out TAKES)
{
	/*~ Write this out, then read the next one.  This works perfectly for
	 * a simple request/response system like this.
	 *
	 * Internally, the ccan/io subsystem gathers all the file descriptors,
	 * figures out which want to write and read, asks the OS which ones
	 * are available, and for those file descriptors, tries to do the
	 * reads/writes we've asked it.  It handles retry in the case where a
	 * read or write is done partially.
	 *
	 * Since the OS does buffering internally (on my system, over 100k
	 * worth) writes will normally succeed immediately.  However, if the
	 * client is slow or malicious, and doesn't read from the socket as
	 * fast as we're writing, eventually the socket buffer will fill up;
	 * we don't care, because ccan/io will wait until there's room to
	 * write this reply before it will read again.  The client just hurts
	 * themselves, and there's no Denial of Service on us.
	 *
	 * If we were to queue outgoing messages ourselves, we *would* have to
	 * consider such scenarios; this is why our daemons generally avoid
	 * buffering from untrusted parties. */
	return io_write_wire(conn, msg_out, client_read_next, c);
}

/*~ Fork+exec our signerd child, wiring one socket between us.  We are the
 * parent; the child inherits our working directory (the lightning network dir),
 * which is where it loads/creates hsm_secret at init time.  This runs before the
 * io_loop, so signerd is ready by the time lightningd sends WIRE_HSMD_INIT. */
static void start_signerd(const char *proxy_argv0)
{
	int fds[2];
	const char *signerd_path;
	pid_t pid;

	if (socketpair(AF_UNIX, SOCK_STREAM, 0, fds) != 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "signerd socketpair: %s", strerror(errno));

	/* Explicit override first, else next to our own binary. */
	signerd_path = getenv("SEQLN_SIGNERD");
	if (!signerd_path)
		signerd_path = path_join(tmpctx,
					 path_dirname(tmpctx, proxy_argv0),
					 "lightning_signerd");

	pid = fork();
	if (pid < 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR, "signerd fork: %s",
			      strerror(errno));

	if (pid == 0) {
		/* Child: become signerd, talking on fds[1]. */
		char fdstr[16];
		close(fds[0]);
		snprintf(fdstr, sizeof(fdstr), "%d", fds[1]);
		execl(signerd_path, "lightning_signerd", fdstr, (char *)NULL);
		/* Only reached on exec failure. */
		fprintf(stderr, "hsmd-proxy: exec signerd (%s) failed: %s\n",
			signerd_path, strerror(errno));
		_exit(127);
	}

	/* Parent: keep our end. */
	close(fds[1]);
	signer_fd = fds[0];
	status_unusual("hsmd-proxy: started signerd pid %d on fd %d (%s)",
		       (int)pid, signer_fd, signerd_path);
}

/*~ SeqLN Tier-2 NETWORK transport.  Instead of fork/exec'ing a local signerd,
 * connect() over TCP to a REMOTE signer at `addr` ("host:port") and use that
 * socket as `signer_fd`.  Everything downstream (forward_to_signer) is unchanged
 * because it only ever sees a framed request/response fd — the transport under
 * it (local UNIX socketpair vs. this TCP socket) is invisible to it.  This is
 * what makes the "we host the node, the device signs remotely" topology real:
 * lightningd + this proxy run on our box, the signer (and the hsm_secret) live
 * on the user's device, reachable at `addr`.
 *
 * ============================= SECURITY (READ ME) =========================
 * This dev transport is RAW TCP: UNAUTHENTICATED and UNENCRYPTED.  The peer at
 * the other end of `signer_fd` fully drives the signer, and the frames carry
 * signing requests for the node's funds.  Anyone who can reach the remote
 * listener (or MITM this connection) can request signatures.  This proves the
 * topology ONLY.  Production MUST wrap this in an authenticated, encrypted
 * channel (Noise/TLS) with per-wallet auth before it touches real keys or a
 * public network.  Mirrored in contrib/seqln-signer/src/bin/seqln-signer.rs.
 * ==========================================================================
 */
static void connect_remote_signer(const char *addr)
{
	char *host, *port, *colon;
	struct addrinfo hints, *res, *ai;
	int fd = -1, gai, one = 1;

	/* Split "host:port" on the LAST colon (so bracketless IPv6 literals
	 * still misparse loudly rather than silently; use host:port for demo). */
	colon = strrchr(addr, ':');
	if (!colon || colon == addr)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "SEQLN_SIGNER_ADDR must be host:port, got '%s'",
			      addr);
	host = tal_strndup(tmpctx, addr, colon - addr);
	port = tal_strdup(tmpctx, colon + 1);

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	gai = getaddrinfo(host, port, &hints, &res);
	if (gai != 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "remote signer resolve %s:%s: %s",
			      host, port, gai_strerror(gai));

	for (ai = res; ai; ai = ai->ai_next) {
		fd = socket(ai->ai_family, ai->ai_socktype, ai->ai_protocol);
		if (fd < 0)
			continue;
		if (connect(fd, ai->ai_addr, ai->ai_addrlen) == 0)
			break;
		close(fd);
		fd = -1;
	}
	freeaddrinfo(res);

	if (fd < 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "remote signer connect %s:%s failed: %s",
			      host, port, strerror(errno));

	/* Low latency for the synchronous per-sign round-trips. */
	setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));

	signer_fd = fd;
	status_unusual("hsmd-proxy: connected to REMOTE signer at %s:%s on fd %d"
		       " (raw TCP, UNAUTHENTICATED dev transport)",
		       host, port, signer_fd);
}

/*~ Forward one request to signerd and relay its reply to the client.  This is
 * the drop-in replacement for the monolithic hsmd's
 * `req_reply(..., hsmd_handle_client_message(...))`.  It is a synchronous
 * round-trip; the whole hsmd protocol is request/response so blocking the io
 * loop here is exactly the monolithic behaviour. */
static struct io_plan *forward_to_signer(struct io_conn *conn,
					 struct client *c,
					 const u8 *msg_in)
{
	bool is_main = (c->dbid == 0);
	enum hsmd_wire reqt = fromwire_peektype(msg_in);
	u8 *reply;

	if (!signer_write_request(signer_fd, is_main, &c->id, c->dbid,
				  c->capabilities, msg_in))
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "signerd write (%s) failed: %s",
			      hsmd_wire_name(reqt), strerror(errno));

	reply = signer_read_reply(tmpctx, signer_fd);
	if (!reply)
		status_failed(STATUS_FAIL_INTERNAL_ERROR,
			      "signerd closed connection on %s",
			      hsmd_wire_name(reqt));

	/* Zero-length reply is signerd's error sentinel. */
	if (tal_bytelen(reply) == 0)
		return bad_req_fmt(conn, c, msg_in,
				   "signerd rejected request %s",
				   hsmd_wire_name(reqt));

	status_debug("hsmd-proxy: %s (dbid=%"PRIu64") -> signerd -> %s",
		     hsmd_wire_name(reqt), c->dbid,
		     hsmd_wire_name(fromwire_peektype(reply)));

	return req_reply(conn, c, take(reply));
}

/*~ We have a pre-init call in developer mode, to set dev flags */
static struct io_plan *preinit_hsm(struct io_conn *conn,
				   struct client *c,
				   const u8 *msg_in)
{
	struct tlv_hsmd_dev_preinit_tlvs *tlv;
	assert(developer);

	if (!fromwire_hsmd_dev_preinit(tmpctx, msg_in, &tlv))
		return bad_req(conn, c, msg_in);

	if (tlv->fail_preapprove)
		dev_fail_preapprove = *tlv->fail_preapprove;

	if (tlv->no_preapprove_check)
		dev_no_preapprove_check = *tlv->no_preapprove_check;

	if (tlv->warn_on_overgrind)
		dev_warn_on_overgrind = *tlv->warn_on_overgrind;

	status_debug("preinit: dev_fail_preapprove = %u, dev_no_preapprove_check = %u, dev_warn_on_overgrind = %u",
		     dev_fail_preapprove, dev_no_preapprove_check, dev_warn_on_overgrind);
	/* We don't send a reply, just read next */
	return client_read_next(conn, c);
}

/*~ Since we process requests then service them in strict order, and because
 * only lightningd can request a new client fd, we can get away with a global
 * here!  But because we are being tricky, I set it to an invalid value when
 * not in use, and sprinkle assertions around. */
static int pending_client_fd = -1;

/*~ This is the callback from below: having sent the reply, we now send the
 * fd for the client end of the new socketpair. */
static struct io_plan *send_pending_client_fd(struct io_conn *conn,
					      struct client *master)
{
	int fd = pending_client_fd;
	/* This must be the master. */
	assert(is_lightningd(master));
	assert(fd != -1);

	/* This sanity check shouldn't be necessary, but it's cheap. */
	pending_client_fd = -1;

	/*~There's arcane UNIX magic to send an open file descriptor over a
	 * UNIX domain socket.  There's no great way to autogenerate this
	 * though; especially for the receive side, so we always pass these
	 * manually immediately following the message.
	 *
	 * io_send_fd()'s third parameter is whether to close the local one
	 * after sending; that saves us YA callback.
	 */
	return io_send_fd(conn, fd, true, client_read_next, master);
}

/*~ This is used by the master to create a new client connection (which
 * becomes the HSM_FD for the subdaemon after forking). */
static struct io_plan *pass_client_hsmfd(struct io_conn *conn,
					 struct client *c,
					 const u8 *msg_in)
{
	int fds[2];
	u64 dbid, capabilities;
	struct node_id id;

	/* This must be lightningd itself. */
	assert(is_lightningd(c));

	if (!fromwire_hsmd_client_hsmfd(msg_in, &id, &dbid, &capabilities))
		return bad_req(conn, c, msg_in);

	/* socketpair is a bi-directional pipe, which is what we want. */
	if (socketpair(AF_UNIX, SOCK_STREAM, 0, fds) != 0)
		status_failed(STATUS_FAIL_INTERNAL_ERROR, "creating fds: %s",
			      strerror(errno));

	status_debug("new_client: %"PRIu64, dbid);
	new_client(c, c->chainparams, &id, dbid, capabilities, fds[0]);

	/*~ We stash this in a global, because we need to get both the fd and
	 * the client pointer to the callback.  The other way would be to
	 * create a boutique structure and hand that, but we don't need to. */
	pending_client_fd = fds[1];
	return io_write_wire(conn, take(towire_hsmd_client_hsmfd_reply(NULL)),
			     send_pending_client_fd, c);
}

static struct io_plan *handle_memleak(struct io_conn *conn,
				      struct client *c,
				      const u8 *msg_in)
{
	struct htable *memtable;
	bool found_leak;
	u8 *reply;

	memtable = memleak_start(tmpctx);
	memleak_ptr(memtable, msg_in);

	/* Now note clients and anything they point to. */
	memleak_scan_region(memtable, dbid_zero_clients, sizeof(dbid_zero_clients));
	memleak_scan_uintmap(memtable, &clients);
	memleak_scan_obj(memtable, status_conn);

	memleak_ptr(memtable, dev_force_privkey);
	memleak_ptr(memtable, dev_force_bip32_seed);

	found_leak = dump_memleak(memtable, memleak_status_broken, NULL);
	reply = towire_hsmd_dev_memleak_reply(NULL, found_leak);
	return req_reply(conn, c, take(reply));
}

u8 *hsmd_status_bad_request(struct hsmd_client *client, const u8 *msg, const char *error)
{
	/* Extract the pointer to the hsmd representation of the
	 * client which has access to the underlying connection. */
	struct client *c = (struct client*)client->extra;
	bad_req_fmt(c->conn, c, msg, "%s", error);

	/* We often use `return hsmd_status_bad_request` to drop out, and NULL
	 * means we encountered an error. */
	return NULL;
}

void hsmd_status_fmt(enum log_level level, const struct node_id *peer,
		     const char *fmt, ...)
{
	va_list ap;

	va_start(ap, fmt);
	status_vfmt(level, peer, fmt, ap);
	va_end(ap);
}

void hsmd_status_failed(enum status_failreason reason, const char *fmt, ...)
{
	va_list ap;
	char *str;

	va_start(ap, fmt);
	str = tal_vfmt(NULL, fmt, ap);
	va_end(ap);

	/* Give a nice backtrace when this happens! */
	if (reason == STATUS_FAIL_INTERNAL_ERROR)
		send_backtrace(str);

	status_send_fatal(take(towire_status_fail(NULL, reason, str)));
}

/*~ This is the core of the HSM daemon: handling requests. */
static struct io_plan *handle_client(struct io_conn *conn, struct client *c)
{
	enum hsmd_wire t = fromwire_peektype(c->msg_in);

	if (!is_lightningd(c))
		status_peer_debug(&c->id, "Got %s", hsmd_wire_name(t));

	/* Before we do anything else, is this client allowed to do
	 * what he asks for? */
	if (!hsmd_check_client_capabilities(c->hsmd_client, t))
		return bad_req_fmt(conn, c, c->msg_in,
				   "client does not have capability to run %d",
				   t);

	/* Now actually go and do what the client asked for */
	switch (t) {
	case WIRE_HSMD_DEV_PREINIT:
		/* Dev-only: keep local (sets this process's libhsmd dev flags).
		 * The dev-forced-key flags are not plumbed to signerd in M1;
		 * we don't run the split node in developer mode. */
		return preinit_hsm(conn, c, c->msg_in);

	case WIRE_HSMD_CLIENT_HSMFD:
		/* LOAD-BEARING: fd multiplexing stays local (SCM_RIGHTS). */
		return pass_client_hsmfd(conn, c, c->msg_in);

	case WIRE_HSMD_DEV_MEMLEAK:
		if (!developer)
			break;
		return handle_memleak(conn, c, c->msg_in);

	/* Everything below needs the root secret, so it is forwarded to the
	 * out-of-process signerd (init + bip86 check included: signerd owns the
	 * secret and special-cases them, mirroring the monolithic hsmd). */
	case WIRE_HSMD_INIT:
	case WIRE_HSMD_CHECK_BIP86_PUBKEY:
	case WIRE_HSMD_NEW_CHANNEL:
	case WIRE_HSMD_SETUP_CHANNEL:
 	case WIRE_HSMD_CHECK_OUTPOINT:
 	case WIRE_HSMD_LOCK_OUTPOINT:
 	case WIRE_HSMD_FORGET_CHANNEL:
	case WIRE_HSMD_SIGN_COMMITMENT_TX:
	case WIRE_HSMD_VALIDATE_COMMITMENT_TX:
	case WIRE_HSMD_REVOKE_COMMITMENT_TX:
	case WIRE_HSMD_VALIDATE_REVOCATION:
	case WIRE_HSMD_SIGN_PENALTY_TO_US:
	case WIRE_HSMD_SIGN_REMOTE_COMMITMENT_TX:
	case WIRE_HSMD_SIGN_REMOTE_HTLC_TX:
	case WIRE_HSMD_SIGN_MUTUAL_CLOSE_TX:
	case WIRE_HSMD_SIGN_SPLICE_TX:
	case WIRE_HSMD_GET_PER_COMMITMENT_POINT:
	case WIRE_HSMD_SIGN_WITHDRAWAL:
	case WIRE_HSMD_GET_CHANNEL_BASEPOINTS:
	case WIRE_HSMD_SIGN_INVOICE:
	case WIRE_HSMD_SIGN_MESSAGE:
	case WIRE_HSMD_BIP137_SIGN_MESSAGE:
	case WIRE_HSMD_SIGN_OPTION_WILL_FUND_OFFER:
	case WIRE_HSMD_SIGN_BOLT12:
	case WIRE_HSMD_SIGN_BOLT12_2:
	case WIRE_HSMD_PREAPPROVE_INVOICE:
	case WIRE_HSMD_PREAPPROVE_KEYSEND:
	case WIRE_HSMD_PREAPPROVE_INVOICE_CHECK:
	case WIRE_HSMD_PREAPPROVE_KEYSEND_CHECK:
	case WIRE_HSMD_ECDH_REQ:
	case WIRE_HSMD_CHECK_FUTURE_SECRET:
	case WIRE_HSMD_GET_OUTPUT_SCRIPTPUBKEY:
	case WIRE_HSMD_DERIVE_SECRET:
	case WIRE_HSMD_CANNOUNCEMENT_SIG_REQ:
	case WIRE_HSMD_SIGN_ANY_CANNOUNCEMENT_REQ:
	case WIRE_HSMD_NODE_ANNOUNCEMENT_SIG_REQ:
	case WIRE_HSMD_CUPDATE_SIG_REQ:
	case WIRE_HSMD_SIGN_REMOTE_HTLC_TO_US:
	case WIRE_HSMD_SIGN_DELAYED_PAYMENT_TO_US:
	case WIRE_HSMD_CHECK_PUBKEY:
	case WIRE_HSMD_SIGN_ANY_PENALTY_TO_US:
	case WIRE_HSMD_SIGN_ANY_DELAYED_PAYMENT_TO_US:
	case WIRE_HSMD_SIGN_ANY_REMOTE_HTLC_TO_US:
	case WIRE_HSMD_SIGN_ANY_LOCAL_HTLC_TX:
	case WIRE_HSMD_SIGN_ANCHORSPEND:
	case WIRE_HSMD_SIGN_HTLC_TX_MINGLE:
		/* Forward to the out-of-process signer. */
		return forward_to_signer(conn, c, c->msg_in);

	case WIRE_HSMD_ECDH_RESP:
	case WIRE_HSMD_CANNOUNCEMENT_SIG_REPLY:
	case WIRE_HSMD_CUPDATE_SIG_REPLY:
	case WIRE_HSMD_CLIENT_HSMFD_REPLY:
	case WIRE_HSMD_NEW_CHANNEL_REPLY:
	case WIRE_HSMD_SETUP_CHANNEL_REPLY:
	case WIRE_HSMD_CHECK_OUTPOINT_REPLY:
	case WIRE_HSMD_LOCK_OUTPOINT_REPLY:
 	case WIRE_HSMD_FORGET_CHANNEL_REPLY:
	case WIRE_HSMD_NODE_ANNOUNCEMENT_SIG_REPLY:
	case WIRE_HSMD_SIGN_WITHDRAWAL_REPLY:
	case WIRE_HSMD_SIGN_INVOICE_REPLY:
	case WIRE_HSMD_INIT_REPLY_V4:
	case WIRE_HSMD_INIT_REPLY_FAILURE:
	case WIRE_HSMD_DERIVE_SECRET_REPLY:
	case WIRE_HSMSTATUS_CLIENT_BAD_REQUEST:
	case WIRE_HSMD_SIGN_COMMITMENT_TX_REPLY:
	case WIRE_HSMD_VALIDATE_COMMITMENT_TX_REPLY:
	case WIRE_HSMD_REVOKE_COMMITMENT_TX_REPLY:
	case WIRE_HSMD_VALIDATE_REVOCATION_REPLY:
	case WIRE_HSMD_SIGN_TX_REPLY:
	case WIRE_HSMD_SIGN_OPTION_WILL_FUND_OFFER_REPLY:
	case WIRE_HSMD_GET_PER_COMMITMENT_POINT_REPLY:
	case WIRE_HSMD_CHECK_FUTURE_SECRET_REPLY:
	case WIRE_HSMD_GET_CHANNEL_BASEPOINTS_REPLY:
	case WIRE_HSMD_DEV_MEMLEAK_REPLY:
	case WIRE_HSMD_SIGN_MESSAGE_REPLY:
	case WIRE_HSMD_BIP137_SIGN_MESSAGE_REPLY:
	case WIRE_HSMD_GET_OUTPUT_SCRIPTPUBKEY_REPLY:
	case WIRE_HSMD_SIGN_BOLT12_REPLY:
	case WIRE_HSMD_SIGN_BOLT12_2_REPLY:
	case WIRE_HSMD_PREAPPROVE_INVOICE_REPLY:
	case WIRE_HSMD_PREAPPROVE_KEYSEND_REPLY:
	case WIRE_HSMD_PREAPPROVE_INVOICE_CHECK_REPLY:
	case WIRE_HSMD_PREAPPROVE_KEYSEND_CHECK_REPLY:
	case WIRE_HSMD_CHECK_PUBKEY_REPLY:
	case WIRE_HSMD_CHECK_BIP86_PUBKEY_REPLY:
	case WIRE_HSMD_SIGN_ANCHORSPEND_REPLY:
	case WIRE_HSMD_SIGN_HTLC_TX_MINGLE_REPLY:
	case WIRE_HSMD_SIGN_ANY_CANNOUNCEMENT_REPLY:
		return bad_req_fmt(conn, c, c->msg_in,
				   "Received an incoming message of type %s, "
				   "which is not a request",
				   hsmd_wire_name(t));
	}

	return bad_req_fmt(conn, c, c->msg_in, "Unknown request");
}

static void master_gone(struct io_conn *unused UNUSED, struct client *c UNUSED)
{
	daemon_shutdown();
	/* Can't tell master, it's gone. */
	exit(2);
}

int main(int argc, char *argv[])
{
	struct client *master;

	setup_locale();

	/* This sets up tmpctx, various --developer options, backtraces, etc. */
	developer = subdaemon_setup(argc, argv);

	/* A trivial daemon_conn just for writing. */
	status_conn = daemon_conn_new(NULL, STDIN_FILENO, NULL, NULL, NULL);
	status_setup_async(status_conn);
	uintmap_init(&clients);

	/*~ Bring up the signer before we start serving lightningd, so it is
	 * ready for the very first request (WIRE_HSMD_INIT).  Two transports:
	 *  - SEQLN_SIGNER_ADDR="host:port" set => connect() to a REMOTE signer
	 *    over TCP (Tier-2 "the device signs remotely" topology).
	 *  - otherwise (default/fallback) => fork+exec a LOCAL signerd. */
	{
		const char *remote_addr = getenv("SEQLN_SIGNER_ADDR");
		if (remote_addr && remote_addr[0] != '\0')
			connect_remote_signer(remote_addr);
		else
			start_signerd(argv[0]);
	}

	master = new_client(NULL, NULL, NULL, 0,
			    HSM_PERM_MASTER | HSM_PERM_SIGN_GOSSIP | HSM_PERM_ECDH,
			    REQ_FD);

	/* First client == lightningd. */
	assert(is_lightningd(master));

	/* When conn closes, everything is freed. */
	io_set_finish(master->conn, master_gone, master);

	/*~ The two NULL args are a list of timers, and the timer which expired:
	 * we don't have any timers. */
	io_loop(NULL, NULL);

	/*~ This should never be reached: io_loop only exits on io_break which
	 * we don't call, a timer expiry which we don't have, or all connections
	 * being closed, and closing the master calls master_gone. */
	abort();
}

/*~ Congratulations on making it through the first of the seven dwarves!
 * (And Christian wondered why I'm so fond of having separate daemons!).
 *
 * We continue our story in the next-more-complex daemon: connectd/connectd.c
 */
